# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccType', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccNo', models.IntegerField()),
                ('Balance', models.FloatField()),
                ('AccType', models.CharField(max_length=60)),
                ('OpenDate', models.DateField()),
                ('AccStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.IntegerField()),
                ('UserType', models.CharField(max_length=50)),
                ('PublicKey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.IntegerField()),
                ('UserType', models.CharField(max_length=50)),
                ('AccessPrivilege', models.CharField(default='RE1', max_length=30)),
                ('PIIAccess', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PIIInfo',
            fields=[
                ('SSN', models.TextField(primary_key=True, serialize=False)),
                ('VisaStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateField()),
                ('Detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=50)),
                ('Assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.InternalUser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransDate', models.DateField()),
                ('TransType', models.CharField(max_length=20)),
                ('Amount', models.FloatField()),
                ('TransStatus', models.CharField(max_length=20)),
                ('SendAcc', models.IntegerField()),
                ('RecAcc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.IntegerField()),
                ('UserType', models.CharField(max_length=50)),
                ('UserOperation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='TaskDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Transaction'),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='SSN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.PIIInfo'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.ExternalUser'),
        ),
        migrations.AddField(
            model_name='accountopen',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.ExternalUser'),
        ),
    ]
