# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccNo', models.IntegerField()),
                ('Balance', models.FloatField()),
                ('AccType', models.CharField(max_length=60)),
                ('OpenDate', models.DateField()),
                ('AccStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.IntegerField()),
                ('UserType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransDate', models.DateField()),
                ('TransType', models.CharField(max_length=20)),
                ('Amount', models.FloatField()),
                ('TransStatus', models.CharField(max_length=20)),
                ('SendAcc', models.IntegerField()),
                ('RecAcc', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.ExternalUser'),
        ),
    ]
