# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_externaluser_publickey'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.IntegerField()),
                ('AccessPrivilege', models.CharField(default='RE1', max_length=30)),
                ('PIIAccess', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PII',
            fields=[
                ('SSN', models.TextField(primary_key=True, serialize=False)),
                ('VisaStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=50)),
                ('TaskDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='internaluser',
            name='SSN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.PII'),
        ),
    ]
