# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20171022_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.InternalUser'),
        ),
    ]
