# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='UserType',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
