# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20171022_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PII',
            new_name='PIIInfo',
        ),
    ]
