# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='UserOperation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
