# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_userdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='Username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
